#构建分布概率
c1=c(0,0,0.1,0.1)
c2=c(0,0.1,0.3,0.1)
c3=c(0.1,0.1,0.1,0)
p=c(c1,c2,c3)
Pdis=matrix(p,byrow=TRUE,3)
Rdis=matrix(c(4,6,8),byrow=TRUE,1)
Sdis=matrix(c(-10,0,10,20),byrow=TRUE,4)
#标准误的计算
ERraw=Rdis%*%Pdis
ER2raw=Rdis^2%*%Pdis
ER=rowSums(ERraw)
ER2=rowSums(ER2raw)
VR=ER2-ER^2
ESraw=Pdis%*%Sdis
ES2raw=Pdis%*%Sdis^2
ES=colSums(ESraw)
ES2=colSums((ES2raw))
VS=ES2-ES^2
sd=sqrt(VS*VR)
print(sd)
#计算协方差
RSdis=Sdis%*%Rdis
RS=t(RSdis)
ERSraw=RS*Pdis
ERS=sum(ERSraw)
covRS=ERS-ER*ES
print(covRS)
#计算相关系数
corRS=covRS/sd
print(corRS)